Fixes for Kodi19+, PM4K compatibility
romanvm/service.addic7ed pull request #34
Opened 2024-01-17 11:41 UTC by pannal

* Update addon.xml for Kodi19+ compatibility
* Update episode info handling; Add compatibility for PM4K's 'videoinfo.current_path' property

2024-01-17 11:44 UTC, pannal commented
Wait, PR https://github.com/romanvm/service.addic7ed/pull/28 was merged already but I don't see the changes in the master branch. I'm confused.

Edit: [This](https://github.com/romanvm/service.addic7ed/blob/master/service.subtitles.rvm.addic7ed/addic7ed/utils.py#L59) is in the current master. What am I missing? Was there a force push inbetween?

2024-01-21 20:57 UTC, romanvm requested changes

2024-01-21 20:57 UTC, romanvm commented on service.subtitles.rvm.addic7ed/addon.xml
> +  <import addon="xbmc.python" version="3.0.0"/>
No need because matrix submission is handled automatically by addon-submitter script.

2024-01-21 20:57 UTC, romanvm commented on service.subtitles.rvm.addic7ed/addic7ed/utils.py
> +    path = xbmc.getInfoLabel('Window(10000).Property(videoinfo.current_path)')
Why this method should be used and what it's advantage over `getPlayingFile()`?

2024-01-21 21:00 UTC, romanvm commented
> Wait, PR #28 was merged already but I don't see the changes in the master branch. I'm confused.

The changes were reverted because they produced incorrect results. That is why I'm hesitant about those changes as well. What is the motivation behind them?

2024-01-22 13:23 UTC, pannal commented on service.subtitles.rvm.addic7ed/addic7ed/utils.py
> +    path = xbmc.getInfoLabel('Window(10000).Property(videoinfo.current_path)')
Because there are cases when `getPlayingFile()` returns a URL and not a filename that's useful (in the case of Plex4Kodi, PM4K, and possibly other player clients implemented in Kodi). The addons can set the correct filename using the global info label and the addic7ed plugin can pick it up.

If that's not set by any addon, it will fall back to `getPlayingFile()`.

This is not a standard info label that's usually there, I've created this way of providing filenames to subtitle addons explicitly for the PM4K/Plex4Kodi case. It's also already supported by the OpenSubtitles.com addon.

2024-01-22 13:32 UTC, pannal commented
> The changes were reverted because they produced incorrect results. That is why I'm hesitant about those changes as well. What is the motivation behind them?

Those changes only provide a fallback to the respective info labels, and still use the old JSON method primarily. If those are non existant for any reason, it uses the info labels.

2024-01-28 09:31 UTC, romanvm requested changes
Please revert `addon.xml`

2024-01-28 09:31 UTC, romanvm commented on service.subtitles.rvm.addic7ed/addic7ed/utils.py
> +    path = xbmc.getInfoLabel('Window(10000).Property(videoinfo.current_path)')
Ok, then. Please revert `addon.xml` and the PR will be merged.

2024-02-11 01:03 UTC, pannal commented
Done

2024-02-11 11:27 UTC, romanvm approved these changes

2024-02-13 18:56 UTC, merged